version = 0.1

[default.deploy.parameters]
stack_name = "peter-task-management-api"
resolve_s3 = true
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_prefix = "peter-task-management-api"
region = "ap-southeast-1"
disable_rollback = true
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
